export const heresHow1Data = [
  {
    id: 1,
    para: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    ques1: "1. What is the IDBI bank Offer?",
    ans1: [
      "a)       Get 10% instant discount on IDBI Bank Credit and Debit Card transactions",
      "b)       Any cancelled, rejected or returned order(s) will not be eligible for the offer and the refund amount of such order will be adjusted with the instant discount amount.",
    ],
    ques2:
      "2. Would I get the Bank offer even if I make a part payment using my Amazon Pay Balance?",
    ans2: "Yes, the offer is available on partial payments as long as minimum purchase value is spent on IDBI bank Card. The customer cannot use EMI option if Amazon Pay balance is selected.",
    ques3: "3. What if I cancel my order?",
    ans3: "The Offer is applicable for a successful purchase. If Instant Discount is availed on any purchase, and it is subsequently cancelled, the refund amount of such purchases will be posted adjusting the instant discount amount availed on the purchase. However, if you place another order within the offer period, you shall get instant bank discount subject to offer eligibility.",
    ques4:
      "4. My payment failed while placing the order, will I be eligible for the cashback?",
    ans4: "If your payment failed while placing the order, Amazon.in gives you an option to revise your payment. If you revise your payment within the offer duration, you will be eligible for the cashback. For more information on revise payment, click here",
    head2: "Terms and Conditions",
    termsAndConditions: [
      "(1) -       This  is provided to you by IDBI Bank Limited and Amazon Pay (India) Private Limited (formerly known as Amazon Online Distribution Services Private Limited) and made available on the website www.amazon.in and the mobile site and mobile application thereof (collectively).",
      "(2) -       These Offer terms and conditions  are in addition to the Amazon.in Conditions of Use & Sale and Privacy Notice to which you agree to by using Amazon.in. In the event of any conflict between the Conditions of Use & Sale and these Offer Terms, these Offer Terms will prevail, only for the purposes of this Offer.",
      "(3) -       All residents of India holding a valid credit and Debit card issued by the Bank are eligible to avail the Offer.",
      "(4).       The offer is valid in the month of March 2023 i.e. 2nd to 31st March, unless revoked or extended by Amazon in its sole discretion, without any prior notice and without liability.",
      "(5) -      Under this Offer, any Cardholder who, during the Offer Duration, makes any purchase of Products from Amazon.in and makes the payment using the Card, will be entitled to receive an instant discount of 10% of the total purchase value for a successful purchase transaction made on Amazon.in, provided the purchase value for such transaction (inclusive of taxes) is equivalent to or exceeds INR 2,000 on Large Appliances, Electronics, Fashion, Beauty, TV, devices, Media, Home, Kitchen and Furniture- per card per transaction.",
      "(6) -       The purchase of the product(s) will be governed by the terms of sale, including terms of exchange (wherever available), applicable to the sale of the product(s) on Amazon.in. This Offer will also be applicable on purchase of product(s) by the Cardholders under an exchange offer.",
      "(7) -    In the event the order is returned or cancelled by the Cardholder, seller or Amazon Seller Services Private Limited, for any reason whatsoever, and subsequently the order / purchase transaction value falls below INR 5000 per transaction the order will not qualify for this Offer and the participation of the Cardholder will be deemed withdrawn.",
      "(8) -    Amazon reserves the right, at any time, without prior notice, without liability, and without assigning any reason whatsoever, to add/alter/modify/change or vary all of these Offer Terms or to replace, wholly or in part, this Offer by another offer, whether similar to this Offer or not.",
    ],
  },
  {
    id: 2,
    para: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    ques1: "1. What is the IDBI bank Offer?",
    ans1: [
      "a)       Get 10% instant discount on IDBI Bank Credit and Debit Card transactions",
      "b)       Any cancelled, rejected or returned order(s) will not be eligible for the offer and the refund amount of such order will be adjusted with the instant discount amount.",
    ],
    ques2:
      "2. Would I get the Bank offer even if I make a part payment using my Amazon Pay Balance?",
    ans2: "Yes, the offer is available on partial payments as long as minimum purchase value is spent on IDBI bank Card. The customer cannot use EMI option if Amazon Pay balance is selected.",
    ques3: "3. What if I cancel my order?",
    ans3: "The Offer is applicable for a successful purchase. If Instant Discount is availed on any purchase, and it is subsequently cancelled, the refund amount of such purchases will be posted adjusting the instant discount amount availed on the purchase. However, if you place another order within the offer period, you shall get instant bank discount subject to offer eligibility.",
    ques4:
      "4. My payment failed while placing the order, will I be eligible for the cashback?",
    ans4: "If your payment failed while placing the order, Amazon.in gives you an option to revise your payment. If you revise your payment within the offer duration, you will be eligible for the cashback. For more information on revise payment, click here",
    head2: "Terms and Conditions",
    termsAndConditions: [
      "(1) -       This  is provided to you by IDBI Bank Limited and Amazon Pay (India) Private Limited (formerly known as Amazon Online Distribution Services Private Limited) and made available on the website www.amazon.in and the mobile site and mobile application thereof (collectively).",
      "(2) -       These Offer terms and conditions  are in addition to the Amazon.in Conditions of Use & Sale and Privacy Notice to which you agree to by using Amazon.in. In the event of any conflict between the Conditions of Use & Sale and these Offer Terms, these Offer Terms will prevail, only for the purposes of this Offer.",
      "(3) -       All residents of India holding a valid credit and Debit card issued by the Bank are eligible to avail the Offer.",
      "(4).       The offer is valid in the month of March 2023 i.e. 2nd to 31st March, unless revoked or extended by Amazon in its sole discretion, without any prior notice and without liability.",
      "(5) -      Under this Offer, any Cardholder who, during the Offer Duration, makes any purchase of Products from Amazon.in and makes the payment using the Card, will be entitled to receive an instant discount of 10% of the total purchase value for a successful purchase transaction made on Amazon.in, provided the purchase value for such transaction (inclusive of taxes) is equivalent to or exceeds INR 2,000 on Large Appliances, Electronics, Fashion, Beauty, TV, devices, Media, Home, Kitchen and Furniture- per card per transaction.",
      "(6) -       The purchase of the product(s) will be governed by the terms of sale, including terms of exchange (wherever available), applicable to the sale of the product(s) on Amazon.in. This Offer will also be applicable on purchase of product(s) by the Cardholders under an exchange offer.",
      "(7) -    In the event the order is returned or cancelled by the Cardholder, seller or Amazon Seller Services Private Limited, for any reason whatsoever, and subsequently the order / purchase transaction value falls below INR 5000 per transaction the order will not qualify for this Offer and the participation of the Cardholder will be deemed withdrawn.",
      "(8) -    Amazon reserves the right, at any time, without prior notice, without liability, and without assigning any reason whatsoever, to add/alter/modify/change or vary all of these Offer Terms or to replace, wholly or in part, this Offer by another offer, whether similar to this Offer or not.",
    ],
  },
  {
    id: 3,
    para: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    ques1: "1. What is the IDBI bank Offer?",
    ans1: [
      "a)       Get 10% instant discount on IDBI Bank Credit and Debit Card transactions",
      "b)       Any cancelled, rejected or returned order(s) will not be eligible for the offer and the refund amount of such order will be adjusted with the instant discount amount.",
    ],
    ques2:
      "2. Would I get the Bank offer even if I make a part payment using my Amazon Pay Balance?",
    ans2: "Yes, the offer is available on partial payments as long as minimum purchase value is spent on IDBI bank Card. The customer cannot use EMI option if Amazon Pay balance is selected.",
    ques3: "3. What if I cancel my order?",
    ans3: "The Offer is applicable for a successful purchase. If Instant Discount is availed on any purchase, and it is subsequently cancelled, the refund amount of such purchases will be posted adjusting the instant discount amount availed on the purchase. However, if you place another order within the offer period, you shall get instant bank discount subject to offer eligibility.",
    ques4:
      "4. My payment failed while placing the order, will I be eligible for the cashback?",
    ans4: "If your payment failed while placing the order, Amazon.in gives you an option to revise your payment. If you revise your payment within the offer duration, you will be eligible for the cashback. For more information on revise payment, click here",
    head2: "Terms and Conditions",
    termsAndConditions: [
      "(1) -       This  is provided to you by IDBI Bank Limited and Amazon Pay (India) Private Limited (formerly known as Amazon Online Distribution Services Private Limited) and made available on the website www.amazon.in and the mobile site and mobile application thereof (collectively).",
      "(2) -       These Offer terms and conditions  are in addition to the Amazon.in Conditions of Use & Sale and Privacy Notice to which you agree to by using Amazon.in. In the event of any conflict between the Conditions of Use & Sale and these Offer Terms, these Offer Terms will prevail, only for the purposes of this Offer.",
      "(3) -       All residents of India holding a valid credit and Debit card issued by the Bank are eligible to avail the Offer.",
      "(4).       The offer is valid in the month of March 2023 i.e. 2nd to 31st March, unless revoked or extended by Amazon in its sole discretion, without any prior notice and without liability.",
      "(5) -      Under this Offer, any Cardholder who, during the Offer Duration, makes any purchase of Products from Amazon.in and makes the payment using the Card, will be entitled to receive an instant discount of 10% of the total purchase value for a successful purchase transaction made on Amazon.in, provided the purchase value for such transaction (inclusive of taxes) is equivalent to or exceeds INR 2,000 on Large Appliances, Electronics, Fashion, Beauty, TV, devices, Media, Home, Kitchen and Furniture- per card per transaction.",
      "(6) -       The purchase of the product(s) will be governed by the terms of sale, including terms of exchange (wherever available), applicable to the sale of the product(s) on Amazon.in. This Offer will also be applicable on purchase of product(s) by the Cardholders under an exchange offer.",
      "(7) -    In the event the order is returned or cancelled by the Cardholder, seller or Amazon Seller Services Private Limited, for any reason whatsoever, and subsequently the order / purchase transaction value falls below INR 5000 per transaction the order will not qualify for this Offer and the participation of the Cardholder will be deemed withdrawn.",
      "(8) -    Amazon reserves the right, at any time, without prior notice, without liability, and without assigning any reason whatsoever, to add/alter/modify/change or vary all of these Offer Terms or to replace, wholly or in part, this Offer by another offer, whether similar to this Offer or not.",
    ],
  },
  {
    id: 4,
    para: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    ques1: "1. What is the IDBI bank Offer?",
    ans1: [
      "a)       Get 10% instant discount on IDBI Bank Credit and Debit Card transactions",
      "b)       Any cancelled, rejected or returned order(s) will not be eligible for the offer and the refund amount of such order will be adjusted with the instant discount amount.",
    ],
    ques2:
      "2. Would I get the Bank offer even if I make a part payment using my Amazon Pay Balance?",
    ans2: "Yes, the offer is available on partial payments as long as minimum purchase value is spent on IDBI bank Card. The customer cannot use EMI option if Amazon Pay balance is selected.",
    ques3: "3. What if I cancel my order?",
    ans3: "The Offer is applicable for a successful purchase. If Instant Discount is availed on any purchase, and it is subsequently cancelled, the refund amount of such purchases will be posted adjusting the instant discount amount availed on the purchase. However, if you place another order within the offer period, you shall get instant bank discount subject to offer eligibility.",
    ques4:
      "4. My payment failed while placing the order, will I be eligible for the cashback?",
    ans4: "If your payment failed while placing the order, Amazon.in gives you an option to revise your payment. If you revise your payment within the offer duration, you will be eligible for the cashback. For more information on revise payment, click here",
    head2: "Terms and Conditions",
    termsAndConditions: [
      "(1) -       This  is provided to you by IDBI Bank Limited and Amazon Pay (India) Private Limited (formerly known as Amazon Online Distribution Services Private Limited) and made available on the website www.amazon.in and the mobile site and mobile application thereof (collectively).",
      "(2) -       These Offer terms and conditions  are in addition to the Amazon.in Conditions of Use & Sale and Privacy Notice to which you agree to by using Amazon.in. In the event of any conflict between the Conditions of Use & Sale and these Offer Terms, these Offer Terms will prevail, only for the purposes of this Offer.",
      "(3) -       All residents of India holding a valid credit and Debit card issued by the Bank are eligible to avail the Offer.",
      "(4).       The offer is valid in the month of March 2023 i.e. 2nd to 31st March, unless revoked or extended by Amazon in its sole discretion, without any prior notice and without liability.",
      "(5) -      Under this Offer, any Cardholder who, during the Offer Duration, makes any purchase of Products from Amazon.in and makes the payment using the Card, will be entitled to receive an instant discount of 10% of the total purchase value for a successful purchase transaction made on Amazon.in, provided the purchase value for such transaction (inclusive of taxes) is equivalent to or exceeds INR 2,000 on Large Appliances, Electronics, Fashion, Beauty, TV, devices, Media, Home, Kitchen and Furniture- per card per transaction.",
      "(6) -       The purchase of the product(s) will be governed by the terms of sale, including terms of exchange (wherever available), applicable to the sale of the product(s) on Amazon.in. This Offer will also be applicable on purchase of product(s) by the Cardholders under an exchange offer.",
      "(7) -    In the event the order is returned or cancelled by the Cardholder, seller or Amazon Seller Services Private Limited, for any reason whatsoever, and subsequently the order / purchase transaction value falls below INR 5000 per transaction the order will not qualify for this Offer and the participation of the Cardholder will be deemed withdrawn.",
      "(8) -    Amazon reserves the right, at any time, without prior notice, without liability, and without assigning any reason whatsoever, to add/alter/modify/change or vary all of these Offer Terms or to replace, wholly or in part, this Offer by another offer, whether similar to this Offer or not.",
    ],
  },
  {
    id: 5,
    para: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    ques1: "1. What is the IDBI bank Offer?",
    ans1: [
      "a)       Get 10% instant discount on IDBI Bank Credit and Debit Card transactions",
      "b)       Any cancelled, rejected or returned order(s) will not be eligible for the offer and the refund amount of such order will be adjusted with the instant discount amount.",
    ],
    ques2:
      "2. Would I get the Bank offer even if I make a part payment using my Amazon Pay Balance?",
    ans2: "Yes, the offer is available on partial payments as long as minimum purchase value is spent on IDBI bank Card. The customer cannot use EMI option if Amazon Pay balance is selected.",
    ques3: "3. What if I cancel my order?",
    ans3: "The Offer is applicable for a successful purchase. If Instant Discount is availed on any purchase, and it is subsequently cancelled, the refund amount of such purchases will be posted adjusting the instant discount amount availed on the purchase. However, if you place another order within the offer period, you shall get instant bank discount subject to offer eligibility.",
    ques4:
      "4. My payment failed while placing the order, will I be eligible for the cashback?",
    ans4: "If your payment failed while placing the order, Amazon.in gives you an option to revise your payment. If you revise your payment within the offer duration, you will be eligible for the cashback. For more information on revise payment, click here",
    head2: "Terms and Conditions",
    termsAndConditions: [
      "(1) -       This  is provided to you by IDBI Bank Limited and Amazon Pay (India) Private Limited (formerly known as Amazon Online Distribution Services Private Limited) and made available on the website www.amazon.in and the mobile site and mobile application thereof (collectively).",
      "(2) -       These Offer terms and conditions  are in addition to the Amazon.in Conditions of Use & Sale and Privacy Notice to which you agree to by using Amazon.in. In the event of any conflict between the Conditions of Use & Sale and these Offer Terms, these Offer Terms will prevail, only for the purposes of this Offer.",
      "(3) -       All residents of India holding a valid credit and Debit card issued by the Bank are eligible to avail the Offer.",
      "(4).       The offer is valid in the month of March 2023 i.e. 2nd to 31st March, unless revoked or extended by Amazon in its sole discretion, without any prior notice and without liability.",
      "(5) -      Under this Offer, any Cardholder who, during the Offer Duration, makes any purchase of Products from Amazon.in and makes the payment using the Card, will be entitled to receive an instant discount of 10% of the total purchase value for a successful purchase transaction made on Amazon.in, provided the purchase value for such transaction (inclusive of taxes) is equivalent to or exceeds INR 2,000 on Large Appliances, Electronics, Fashion, Beauty, TV, devices, Media, Home, Kitchen and Furniture- per card per transaction.",
      "(6) -       The purchase of the product(s) will be governed by the terms of sale, including terms of exchange (wherever available), applicable to the sale of the product(s) on Amazon.in. This Offer will also be applicable on purchase of product(s) by the Cardholders under an exchange offer.",
      "(7) -    In the event the order is returned or cancelled by the Cardholder, seller or Amazon Seller Services Private Limited, for any reason whatsoever, and subsequently the order / purchase transaction value falls below INR 5000 per transaction the order will not qualify for this Offer and the participation of the Cardholder will be deemed withdrawn.",
      "(8) -    Amazon reserves the right, at any time, without prior notice, without liability, and without assigning any reason whatsoever, to add/alter/modify/change or vary all of these Offer Terms or to replace, wholly or in part, this Offer by another offer, whether similar to this Offer or not.",
    ],
  },
  {
    id: 6,
    para: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    ques1: "1. What is the IDBI bank Offer?",
    ans1: [
      "a)       Get 10% instant discount on IDBI Bank Credit and Debit Card transactions",
      "b)       Any cancelled, rejected or returned order(s) will not be eligible for the offer and the refund amount of such order will be adjusted with the instant discount amount.",
    ],
    ques2:
      "2. Would I get the Bank offer even if I make a part payment using my Amazon Pay Balance?",
    ans2: "Yes, the offer is available on partial payments as long as minimum purchase value is spent on IDBI bank Card. The customer cannot use EMI option if Amazon Pay balance is selected.",
    ques3: "3. What if I cancel my order?",
    ans3: "The Offer is applicable for a successful purchase. If Instant Discount is availed on any purchase, and it is subsequently cancelled, the refund amount of such purchases will be posted adjusting the instant discount amount availed on the purchase. However, if you place another order within the offer period, you shall get instant bank discount subject to offer eligibility.",
    ques4:
      "4. My payment failed while placing the order, will I be eligible for the cashback?",
    ans4: "If your payment failed while placing the order, Amazon.in gives you an option to revise your payment. If you revise your payment within the offer duration, you will be eligible for the cashback. For more information on revise payment, click here",
    head2: "Terms and Conditions",
    termsAndConditions: [
      "(1) -       This  is provided to you by IDBI Bank Limited and Amazon Pay (India) Private Limited (formerly known as Amazon Online Distribution Services Private Limited) and made available on the website www.amazon.in and the mobile site and mobile application thereof (collectively).",
      "(2) -       These Offer terms and conditions  are in addition to the Amazon.in Conditions of Use & Sale and Privacy Notice to which you agree to by using Amazon.in. In the event of any conflict between the Conditions of Use & Sale and these Offer Terms, these Offer Terms will prevail, only for the purposes of this Offer.",
      "(3) -       All residents of India holding a valid credit and Debit card issued by the Bank are eligible to avail the Offer.",
      "(4).       The offer is valid in the month of March 2023 i.e. 2nd to 31st March, unless revoked or extended by Amazon in its sole discretion, without any prior notice and without liability.",
      "(5) -      Under this Offer, any Cardholder who, during the Offer Duration, makes any purchase of Products from Amazon.in and makes the payment using the Card, will be entitled to receive an instant discount of 10% of the total purchase value for a successful purchase transaction made on Amazon.in, provided the purchase value for such transaction (inclusive of taxes) is equivalent to or exceeds INR 2,000 on Large Appliances, Electronics, Fashion, Beauty, TV, devices, Media, Home, Kitchen and Furniture- per card per transaction.",
      "(6) -       The purchase of the product(s) will be governed by the terms of sale, including terms of exchange (wherever available), applicable to the sale of the product(s) on Amazon.in. This Offer will also be applicable on purchase of product(s) by the Cardholders under an exchange offer.",
      "(7) -    In the event the order is returned or cancelled by the Cardholder, seller or Amazon Seller Services Private Limited, for any reason whatsoever, and subsequently the order / purchase transaction value falls below INR 5000 per transaction the order will not qualify for this Offer and the participation of the Cardholder will be deemed withdrawn.",
      "(8) -    Amazon reserves the right, at any time, without prior notice, without liability, and without assigning any reason whatsoever, to add/alter/modify/change or vary all of these Offer Terms or to replace, wholly or in part, this Offer by another offer, whether similar to this Offer or not.",
    ],
  },
  {
    id: 7,
    para: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    ques1: "1. What is the IDBI bank Offer?",
    ans1: [
      "a)       Get 10% instant discount on IDBI Bank Credit and Debit Card transactions",
      "b)       Any cancelled, rejected or returned order(s) will not be eligible for the offer and the refund amount of such order will be adjusted with the instant discount amount.",
    ],
    ques2:
      "2. Would I get the Bank offer even if I make a part payment using my Amazon Pay Balance?",
    ans2: "Yes, the offer is available on partial payments as long as minimum purchase value is spent on IDBI bank Card. The customer cannot use EMI option if Amazon Pay balance is selected.",
    ques3: "3. What if I cancel my order?",
    ans3: "The Offer is applicable for a successful purchase. If Instant Discount is availed on any purchase, and it is subsequently cancelled, the refund amount of such purchases will be posted adjusting the instant discount amount availed on the purchase. However, if you place another order within the offer period, you shall get instant bank discount subject to offer eligibility.",
    ques4:
      "4. My payment failed while placing the order, will I be eligible for the cashback?",
    ans4: "If your payment failed while placing the order, Amazon.in gives you an option to revise your payment. If you revise your payment within the offer duration, you will be eligible for the cashback. For more information on revise payment, click here",
    head2: "Terms and Conditions",
    termsAndConditions: [
      "(1) -       This  is provided to you by IDBI Bank Limited and Amazon Pay (India) Private Limited (formerly known as Amazon Online Distribution Services Private Limited) and made available on the website www.amazon.in and the mobile site and mobile application thereof (collectively).",
      "(2) -       These Offer terms and conditions  are in addition to the Amazon.in Conditions of Use & Sale and Privacy Notice to which you agree to by using Amazon.in. In the event of any conflict between the Conditions of Use & Sale and these Offer Terms, these Offer Terms will prevail, only for the purposes of this Offer.",
      "(3) -       All residents of India holding a valid credit and Debit card issued by the Bank are eligible to avail the Offer.",
      "(4).       The offer is valid in the month of March 2023 i.e. 2nd to 31st March, unless revoked or extended by Amazon in its sole discretion, without any prior notice and without liability.",
      "(5) -      Under this Offer, any Cardholder who, during the Offer Duration, makes any purchase of Products from Amazon.in and makes the payment using the Card, will be entitled to receive an instant discount of 10% of the total purchase value for a successful purchase transaction made on Amazon.in, provided the purchase value for such transaction (inclusive of taxes) is equivalent to or exceeds INR 2,000 on Large Appliances, Electronics, Fashion, Beauty, TV, devices, Media, Home, Kitchen and Furniture- per card per transaction.",
      "(6) -       The purchase of the product(s) will be governed by the terms of sale, including terms of exchange (wherever available), applicable to the sale of the product(s) on Amazon.in. This Offer will also be applicable on purchase of product(s) by the Cardholders under an exchange offer.",
      "(7) -    In the event the order is returned or cancelled by the Cardholder, seller or Amazon Seller Services Private Limited, for any reason whatsoever, and subsequently the order / purchase transaction value falls below INR 5000 per transaction the order will not qualify for this Offer and the participation of the Cardholder will be deemed withdrawn.",
      "(8) -    Amazon reserves the right, at any time, without prior notice, without liability, and without assigning any reason whatsoever, to add/alter/modify/change or vary all of these Offer Terms or to replace, wholly or in part, this Offer by another offer, whether similar to this Offer or not.",
    ],
  },
  {
    id: 8,
    para: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    ques1: "1. What is the IDBI bank Offer?",
    ans1: [
      "a)       Get 10% instant discount on IDBI Bank Credit and Debit Card transactions",
      "b)       Any cancelled, rejected or returned order(s) will not be eligible for the offer and the refund amount of such order will be adjusted with the instant discount amount.",
    ],
    ques2:
      "2. Would I get the Bank offer even if I make a part payment using my Amazon Pay Balance?",
    ans2: "Yes, the offer is available on partial payments as long as minimum purchase value is spent on IDBI bank Card. The customer cannot use EMI option if Amazon Pay balance is selected.",
    ques3: "3. What if I cancel my order?",
    ans3: "The Offer is applicable for a successful purchase. If Instant Discount is availed on any purchase, and it is subsequently cancelled, the refund amount of such purchases will be posted adjusting the instant discount amount availed on the purchase. However, if you place another order within the offer period, you shall get instant bank discount subject to offer eligibility.",
    ques4:
      "4. My payment failed while placing the order, will I be eligible for the cashback?",
    ans4: "If your payment failed while placing the order, Amazon.in gives you an option to revise your payment. If you revise your payment within the offer duration, you will be eligible for the cashback. For more information on revise payment, click here",
    head2: "Terms and Conditions",
    termsAndConditions: [
      "(1) -       This  is provided to you by IDBI Bank Limited and Amazon Pay (India) Private Limited (formerly known as Amazon Online Distribution Services Private Limited) and made available on the website www.amazon.in and the mobile site and mobile application thereof (collectively).",
      "(2) -       These Offer terms and conditions  are in addition to the Amazon.in Conditions of Use & Sale and Privacy Notice to which you agree to by using Amazon.in. In the event of any conflict between the Conditions of Use & Sale and these Offer Terms, these Offer Terms will prevail, only for the purposes of this Offer.",
      "(3) -       All residents of India holding a valid credit and Debit card issued by the Bank are eligible to avail the Offer.",
      "(4).       The offer is valid in the month of March 2023 i.e. 2nd to 31st March, unless revoked or extended by Amazon in its sole discretion, without any prior notice and without liability.",
      "(5) -      Under this Offer, any Cardholder who, during the Offer Duration, makes any purchase of Products from Amazon.in and makes the payment using the Card, will be entitled to receive an instant discount of 10% of the total purchase value for a successful purchase transaction made on Amazon.in, provided the purchase value for such transaction (inclusive of taxes) is equivalent to or exceeds INR 2,000 on Large Appliances, Electronics, Fashion, Beauty, TV, devices, Media, Home, Kitchen and Furniture- per card per transaction.",
      "(6) -       The purchase of the product(s) will be governed by the terms of sale, including terms of exchange (wherever available), applicable to the sale of the product(s) on Amazon.in. This Offer will also be applicable on purchase of product(s) by the Cardholders under an exchange offer.",
      "(7) -    In the event the order is returned or cancelled by the Cardholder, seller or Amazon Seller Services Private Limited, for any reason whatsoever, and subsequently the order / purchase transaction value falls below INR 5000 per transaction the order will not qualify for this Offer and the participation of the Cardholder will be deemed withdrawn.",
      "(8) -    Amazon reserves the right, at any time, without prior notice, without liability, and without assigning any reason whatsoever, to add/alter/modify/change or vary all of these Offer Terms or to replace, wholly or in part, this Offer by another offer, whether similar to this Offer or not.",
    ],
  },
  {
    id: 9,
    para: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum",
    ques1: "1. What is the IDBI bank Offer?",
    ans1: [
      "a)       Get 10% instant discount on IDBI Bank Credit and Debit Card transactions",
      "b)       Any cancelled, rejected or returned order(s) will not be eligible for the offer and the refund amount of such order will be adjusted with the instant discount amount.",
    ],
    ques2:
      "2. Would I get the Bank offer even if I make a part payment using my Amazon Pay Balance?",
    ans2: "Yes, the offer is available on partial payments as long as minimum purchase value is spent on IDBI bank Card. The customer cannot use EMI option if Amazon Pay balance is selected.",
    ques3: "3. What if I cancel my order?",
    ans3: "The Offer is applicable for a successful purchase. If Instant Discount is availed on any purchase, and it is subsequently cancelled, the refund amount of such purchases will be posted adjusting the instant discount amount availed on the purchase. However, if you place another order within the offer period, you shall get instant bank discount subject to offer eligibility.",
    ques4:
      "4. My payment failed while placing the order, will I be eligible for the cashback?",
    ans4: "If your payment failed while placing the order, Amazon.in gives you an option to revise your payment. If you revise your payment within the offer duration, you will be eligible for the cashback. For more information on revise payment, click here",
    head2: "Terms and Conditions",
    termsAndConditions: [
      "(1) -       This  is provided to you by IDBI Bank Limited and Amazon Pay (India) Private Limited (formerly known as Amazon Online Distribution Services Private Limited) and made available on the website www.amazon.in and the mobile site and mobile application thereof (collectively).",
      "(2) -       These Offer terms and conditions  are in addition to the Amazon.in Conditions of Use & Sale and Privacy Notice to which you agree to by using Amazon.in. In the event of any conflict between the Conditions of Use & Sale and these Offer Terms, these Offer Terms will prevail, only for the purposes of this Offer.",
      "(3) -       All residents of India holding a valid credit and Debit card issued by the Bank are eligible to avail the Offer.",
      "(4).       The offer is valid in the month of March 2023 i.e. 2nd to 31st March, unless revoked or extended by Amazon in its sole discretion, without any prior notice and without liability.",
      "(5) -      Under this Offer, any Cardholder who, during the Offer Duration, makes any purchase of Products from Amazon.in and makes the payment using the Card, will be entitled to receive an instant discount of 10% of the total purchase value for a successful purchase transaction made on Amazon.in, provided the purchase value for such transaction (inclusive of taxes) is equivalent to or exceeds INR 2,000 on Large Appliances, Electronics, Fashion, Beauty, TV, devices, Media, Home, Kitchen and Furniture- per card per transaction.",
      "(6) -       The purchase of the product(s) will be governed by the terms of sale, including terms of exchange (wherever available), applicable to the sale of the product(s) on Amazon.in. This Offer will also be applicable on purchase of product(s) by the Cardholders under an exchange offer.",
      "(7) -    In the event the order is returned or cancelled by the Cardholder, seller or Amazon Seller Services Private Limited, for any reason whatsoever, and subsequently the order / purchase transaction value falls below INR 5000 per transaction the order will not qualify for this Offer and the participation of the Cardholder will be deemed withdrawn.",
      "(8) -    Amazon reserves the right, at any time, without prior notice, without liability, and without assigning any reason whatsoever, to add/alter/modify/change or vary all of these Offer Terms or to replace, wholly or in part, this Offer by another offer, whether similar to this Offer or not.",
    ],
  },
];
