export const productDetailsData = [
  {
    id: 1,
    productDimensions: "PRODUCT DIMENSIONS : 67 x 31 x 0.5 cm; 540 Grams",
    dateAvailable: "DATE FIRST AVAILABLE : 25 August 2021",
    manufacture: "MANUFACTURE : Raymond Limited (MTM Dept)",
    asin: "ASIN : B09DKGMBDN",
    itemModelnumber: "ITEM MODEL NUMBER : RPDC02150-B8",
    countryOrigin: "COUNTRY OF ORIGIN : India",
    department: "DEPARTMENT : Men",
    manufacturer:
      "MANUFACTURER : Raymond Limited (MTM Dept), RAYMOND LIMITED (MTM DEPT), PRESTIGE STAR 1, MAJOR SANDEEP UNNIKRISHANAN ROAD, BANGALORE,560064",
    packer:
      "PACKER : RAYMOND LIMITED (MTM DEPT), PRESTIGE STAR 1, MAJOR SANDEEP UNNIKRISHANAN ROAD, ,BANGALORE,560064",
    itemWeight: "ITEM WEIGHT : 540 g",
    itemDimension: "ITEM DIMENSIONS LxWxH : 67 x 31 x 0.5 Centimeters",
    genericname: "GENERIC NAME : Suit",
    bestSellerRank:
      "BEST SELLERS RANK: #75,568 in Clothing & Accessories (See Top 100 in Clothing & Accessories)",
  },
  {
    id: 2,
    productDimensions: "PRODUCT DIMENSIONS : 38.1 x 38.1 x 7.62 cm; 300 Grams",
    dateAvailable: "DATE FIRST AVAILABLE : 17 March 2023",
    manufacture: "Manufacturer: Email : razabenterprises@gmail.com",
    asin: "ASIN : B0BYS937BT",
    itemModelnumber: "ITEM MODEL NUMBER : SAAYA-JP-9070",
    countryOrigin: "COUNTRY OF ORIGIN : India",
    department: "DEPARTMENT : Men",
    manufacturer:
      "Manufacturer: Email : razabenterprises@gmail.com, Email : razabenterprises@gmail.com",
    packer: "PACKER : Email : razabenterprises@gmail.com",
    itemWeight: "ITEM WEIGHT : 300 g",
    itemDimension: "ITEM DIMENSIONS LxWxH : 38.1 x 38.1 x 7.6 Centimeters",
    NetQuantity: "NET QUANTITY : 1.00 count",
    bestSellerRank:
      "BEST SELLERS RANK:  #68,328 in Clothing & Accessories (See Top 100 in Clothing & Accessories) #178 in Men's Suits & Blazers",
  },
  {
    id: 3,
    productDimensions: "PRODUCT DIMENSIONS : 15 x 10 x 2 cm; 399 Grams",
    dateAvailable: "DATE FIRST AVAILABLE : 30 December 2021",
    manufacture: "Manufacturer: Dhruvi Trendz",
    asin: "ASIN : B09PGFFDF7",
    itemModelnumber: "ITEM MODEL NUMBER : SAAYA-JP-9070",
    countryOrigin: "COUNTRY OF ORIGIN : India",
    department: "DEPARTMENT : Men",
    manufacturer:
      "Manufacturer: Email : razabenterprises@gmail.com, Email : razabenterprises@gmail.com",
    packer: "PACKER : Email : razabenterprises@gmail.com",
    itemWeight: "ITEM WEIGHT : 300 g",
    itemDimension: "ITEM DIMENSIONS LxWxH : 38.1 x 38.1 x 7.6 Centimeters",
    NetQuantity: "NET QUANTITY : 1.00 count",
    bestSellerRank:
      "BEST SELLERS RANK:  #68,328 in Clothing & Accessories (See Top 100 in Clothing & Accessories) #178 in Men's Suits & Blazers",
  },
  {
    id: 4,
    productDimensions: "PRODUCT DIMENSIONS : 38.1 x 38.1 x 7.62 cm; 300 Grams",
    dateAvailable: "DATE FIRST AVAILABLE : 17 March 2023",
    manufacture: "Manufacturer: Email : razabenterprises@gmail.com",
    asin: "ASIN : B0BYS937BT",
    itemModelnumber: "ITEM MODEL NUMBER : SAAYA-JP-9070",
    countryOrigin: "COUNTRY OF ORIGIN : India",
    department: "DEPARTMENT : Men",
    manufacturer:
      "Manufacturer: Email : razabenterprises@gmail.com, Email : razabenterprises@gmail.com",
    packer: "PACKER : Email : razabenterprises@gmail.com",
    itemWeight: "ITEM WEIGHT : 300 g",
    itemDimension: "ITEM DIMENSIONS LxWxH : 38.1 x 38.1 x 7.6 Centimeters",
    NetQuantity: "NET QUANTITY : 1.00 count",
    bestSellerRank:
      "BEST SELLERS RANK:  #68,328 in Clothing & Accessories (See Top 100 in Clothing & Accessories) #178 in Men's Suits & Blazers",
  },
  {
    id: 5,
    productDimensions: "PRODUCT DIMENSIONS : 38.1 x 38.1 x 7.62 cm; 300 Grams",
    dateAvailable: "DATE FIRST AVAILABLE : 17 March 2023",
    manufacture: "Manufacturer: Email : razabenterprises@gmail.com",
    asin: "ASIN : B0BYS937BT",
    itemModelnumber: "ITEM MODEL NUMBER : SAAYA-JP-9070",
    countryOrigin: "COUNTRY OF ORIGIN : India",
    department: "DEPARTMENT : Men",
    manufacturer:
      "Manufacturer: Email : razabenterprises@gmail.com, Email : razabenterprises@gmail.com",
    packer: "PACKER : Email : razabenterprises@gmail.com",
    itemWeight: "ITEM WEIGHT : 300 g",
    itemDimension: "ITEM DIMENSIONS LxWxH : 38.1 x 38.1 x 7.6 Centimeters",
    NetQuantity: "NET QUANTITY : 1.00 count",
    bestSellerRank:
      "BEST SELLERS RANK:  #68,328 in Clothing & Accessories (See Top 100 in Clothing & Accessories) #178 in Men's Suits & Blazers",
  },
  {
    id: 6,
    productDimensions: "PRODUCT DIMENSIONS : 38.1 x 38.1 x 7.62 cm; 300 Grams",
    dateAvailable: "DATE FIRST AVAILABLE : 17 March 2023",
    manufacture: "Manufacturer: Email : razabenterprises@gmail.com",
    asin: "ASIN : B0BYS937BT",
    itemModelnumber: "ITEM MODEL NUMBER : SAAYA-JP-9070",
    countryOrigin: "COUNTRY OF ORIGIN : India",
    department: "DEPARTMENT : Men",
    manufacturer:
      "Manufacturer: Email : razabenterprises@gmail.com, Email : razabenterprises@gmail.com",
    packer: "PACKER : Email : razabenterprises@gmail.com",
    itemWeight: "ITEM WEIGHT : 300 g",
    itemDimension: "ITEM DIMENSIONS LxWxH : 38.1 x 38.1 x 7.6 Centimeters",
    NetQuantity: "NET QUANTITY : 1.00 count",
    bestSellerRank:
      "BEST SELLERS RANK:  #68,328 in Clothing & Accessories (See Top 100 in Clothing & Accessories) #178 in Men's Suits & Blazers",
  },
  {
    id: 7,
    productDimensions: "PRODUCT DIMENSIONS : 38.1 x 38.1 x 7.62 cm; 300 Grams",
    dateAvailable: "DATE FIRST AVAILABLE : 17 March 2023",
    manufacture: "Manufacturer: Email : razabenterprises@gmail.com",
    asin: "ASIN : B0BYS937BT",
    itemModelnumber: "ITEM MODEL NUMBER : SAAYA-JP-9070",
    countryOrigin: "COUNTRY OF ORIGIN : India",
    department: "DEPARTMENT : Men",
    manufacturer:
      "Manufacturer: Email : razabenterprises@gmail.com, Email : razabenterprises@gmail.com",
    packer: "PACKER : Email : razabenterprises@gmail.com",
    itemWeight: "ITEM WEIGHT : 300 g",
    itemDimension: "ITEM DIMENSIONS LxWxH : 38.1 x 38.1 x 7.6 Centimeters",
    NetQuantity: "NET QUANTITY : 1.00 count",
    bestSellerRank:
      "BEST SELLERS RANK:  #68,328 in Clothing & Accessories (See Top 100 in Clothing & Accessories) #178 in Men's Suits & Blazers",
  },
  {
    id: 8,
    productDimensions: "PRODUCT DIMENSIONS : 38.1 x 38.1 x 7.62 cm; 300 Grams",
    dateAvailable: "DATE FIRST AVAILABLE : 17 March 2023",
    manufacture: "Manufacturer: Email : razabenterprises@gmail.com",
    asin: "ASIN : B0BYS937BT",
    itemModelnumber: "ITEM MODEL NUMBER : SAAYA-JP-9070",
    countryOrigin: "COUNTRY OF ORIGIN : India",
    department: "DEPARTMENT : Men",
    manufacturer:
      "Manufacturer: Email : razabenterprises@gmail.com, Email : razabenterprises@gmail.com",
    packer: "PACKER : Email : razabenterprises@gmail.com",
    itemWeight: "ITEM WEIGHT : 300 g",
    itemDimension: "ITEM DIMENSIONS LxWxH : 38.1 x 38.1 x 7.6 Centimeters",
    NetQuantity: "NET QUANTITY : 1.00 count",
    bestSellerRank:
      "BEST SELLERS RANK:  #68,328 in Clothing & Accessories (See Top 100 in Clothing & Accessories) #178 in Men's Suits & Blazers",
  },
  {
    id: 9,
    productDimensions: "PRODUCT DIMENSIONS : 38.1 x 38.1 x 7.62 cm; 300 Grams",
    dateAvailable: "DATE FIRST AVAILABLE : 17 March 2023",
    manufacture: "Manufacturer: Email : razabenterprises@gmail.com",
    asin: "ASIN : B0BYS937BT",
    itemModelnumber: "ITEM MODEL NUMBER : SAAYA-JP-9070",
    countryOrigin: "COUNTRY OF ORIGIN : India",
    department: "DEPARTMENT : Men",
    manufacturer:
      "Manufacturer: Email : razabenterprises@gmail.com, Email : razabenterprises@gmail.com",
    packer: "PACKER : Email : razabenterprises@gmail.com",
    itemWeight: "ITEM WEIGHT : 300 g",
    itemDimension: "ITEM DIMENSIONS LxWxH : 38.1 x 38.1 x 7.6 Centimeters",
    NetQuantity: "NET QUANTITY : 1.00 count",
    bestSellerRank:
      "BEST SELLERS RANK:  #68,328 in Clothing & Accessories (See Top 100 in Clothing & Accessories) #178 in Men's Suits & Blazers",
  },
];
